import type { Metadata } from "next";
import "./globals.css";

import Header from "../components/nav/Header";
import { Toaster } from 'react-hot-toast'

export const metadata: Metadata = {
  title: "Next Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#6D5D6E]">
        <Header />
        <Toaster />
        {children}
      </body>
    </html>
  );
}
